CREATE TABLE `etf_watchlist` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `symbol` text NOT NULL,
  `name` text NOT NULL,
  `category` text NOT NULL,
  `description` text,
  `active` integer DEFAULT true NOT NULL,
  `created_at` text DEFAULT (datetime('now')) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `etf_watchlist_symbol_unique` ON `etf_watchlist` (`symbol`);
--> statement-breakpoint
INSERT INTO `etf_watchlist` (`symbol`, `name`, `category`, `description`) VALUES
  ('SPY', 'SPDR S&P 500 ETF Trust', 'indices', 'Replica las 500 empresas más grandes de EEUU'),
  ('QQQ', 'Invesco QQQ Trust', 'indices', 'Replica el Nasdaq 100, dominado por tecnología'),
  ('IWM', 'iShares Russell 2000 ETF', 'indices', 'Empresas de pequeña capitalización de EEUU'),
  ('DIA', 'SPDR Dow Jones Industrial Average ETF', 'indices', 'Replica el índice Dow Jones de 30 empresas'),
  ('VT', 'Vanguard Total World Stock ETF', 'indices', 'Mercado global completo en un solo ETF'),
  ('VTI', 'Vanguard Total Stock Market ETF', 'indices', 'Mercado de acciones de EEUU completo'),
  ('XLK', 'Technology Select Sector SPDR Fund', 'sectores', 'Sector tecnología del S&P 500'),
  ('XLE', 'Energy Select Sector SPDR Fund', 'sectores', 'Sector energía del S&P 500'),
  ('XLF', 'Financial Select Sector SPDR Fund', 'sectores', 'Sector financiero del S&P 500'),
  ('XLV', 'Health Care Select Sector SPDR Fund', 'sectores', 'Sector salud del S&P 500'),
  ('XLI', 'Industrial Select Sector SPDR Fund', 'sectores', 'Sector industrial del S&P 500'),
  ('XLY', 'Consumer Discretionary Select Sector SPDR Fund', 'sectores', 'Consumo discrecional del S&P 500'),
  ('XLP', 'Consumer Staples Select Sector SPDR Fund', 'sectores', 'Consumo básico del S&P 500'),
  ('XLU', 'Utilities Select Sector SPDR Fund', 'sectores', 'Sector utilities del S&P 500'),
  ('XLB', 'Materials Select Sector SPDR Fund', 'sectores', 'Sector materiales del S&P 500'),
  ('XLRE', 'Real Estate Select Sector SPDR Fund', 'sectores', 'Real estate del S&P 500'),
  ('XLC', 'Communication Services Select Sector SPDR Fund', 'sectores', 'Comunicaciones del S&P 500'),
  ('SMH', 'VanEck Semiconductor ETF', 'sectores', 'Sector semiconductores global'),
  ('SOXX', 'iShares Semiconductor ETF', 'sectores', 'Semiconductores con mayor diversificación'),
  ('IBB', 'iShares Biotechnology ETF', 'sectores', 'Sector biotecnología de EEUU'),
  ('TLT', 'iShares 20+ Year Treasury Bond ETF', 'bonos', 'Bonos del tesoro de EEUU a largo plazo'),
  ('IEF', 'iShares 7-10 Year Treasury Bond ETF', 'bonos', 'Bonos del tesoro de EEUU a mediano plazo'),
  ('SHY', 'iShares 1-3 Year Treasury Bond ETF', 'bonos', 'Bonos del tesoro de EEUU a corto plazo'),
  ('AGG', 'iShares Core U.S. Aggregate Bond ETF', 'bonos', 'Mercado de bonos de EEUU completo'),
  ('HYG', 'iShares iBoxx High Yield Corporate Bond ETF', 'bonos', 'Bonos corporativos de alto rendimiento'),
  ('LQD', 'iShares iBoxx Investment Grade Corporate Bond ETF', 'bonos', 'Bonos corporativos investment grade'),
  ('EMB', 'iShares JP Morgan USD Emerging Markets Bond ETF', 'bonos', 'Bonos de mercados emergentes en USD'),
  ('TIP', 'iShares TIPS Bond ETF', 'bonos', 'Bonos indexados a inflación de EEUU'),
  ('GLD', 'SPDR Gold Shares', 'commodities', 'Precio del oro físico'),
  ('SLV', 'iShares Silver Trust', 'commodities', 'Precio de la plata física'),
  ('USO', 'United States Oil Fund', 'commodities', 'Precio del petróleo crudo WTI'),
  ('UNG', 'United States Natural Gas Fund', 'commodities', 'Precio del gas natural'),
  ('CORN', 'Teucrium Corn Fund', 'commodities', 'Precio del maíz'),
  ('WEAT', 'Teucrium Wheat Fund', 'commodities', 'Precio del trigo'),
  ('SOYB', 'Teucrium Soybean Fund', 'commodities', 'Precio de la soja'),
  ('EWZ', 'iShares MSCI Brazil ETF', 'latam', 'Mercado de acciones de Brasil'),
  ('ILF', 'iShares Latin America 40 ETF', 'latam', 'Las 40 mayores empresas de Latinoamérica'),
  ('ARGT', 'Global X MSCI Argentina ETF', 'latam', 'Mercado de acciones de Argentina'),
  ('GXG', 'Global X MSCI Colombia ETF', 'latam', 'Mercado de acciones de Colombia'),
  ('ECH', 'iShares MSCI Chile ETF', 'latam', 'Mercado de acciones de Chile'),
  ('EFA', 'iShares MSCI EAFE ETF', 'internacional', 'Mercados desarrollados fuera de EEUU y Canadá'),
  ('EEM', 'iShares MSCI Emerging Markets ETF', 'internacional', 'Mercados emergentes globales'),
  ('EWJ', 'iShares MSCI Japan ETF', 'internacional', 'Mercado de acciones de Japón'),
  ('EWG', 'iShares MSCI Germany ETF', 'internacional', 'Mercado de acciones de Alemania'),
  ('EWU', 'iShares MSCI United Kingdom ETF', 'internacional', 'Mercado de acciones del Reino Unido'),
  ('FXI', 'iShares China Large-Cap ETF', 'internacional', 'Las mayores empresas de China'),
  ('KWEB', 'KraneShares CSI China Internet ETF', 'internacional', 'Internet y tecnología de China'),
  ('INDA', 'iShares MSCI India ETF', 'internacional', 'Mercado de acciones de India'),
  ('IBIT', 'iShares Bitcoin Trust ETF', 'crypto', 'Bitcoin via ETF aprobado por la SEC'),
  ('FBTC', 'Fidelity Wise Origin Bitcoin Fund', 'crypto', 'Bitcoin via ETF de Fidelity'),
  ('ETHA', 'iShares Ethereum Trust ETF', 'crypto', 'Ethereum via ETF aprobado por la SEC'),
  ('VTV', 'Vanguard Value ETF', 'factor', 'Acciones de valor del mercado EEUU'),
  ('VUG', 'Vanguard Growth ETF', 'factor', 'Acciones de crecimiento del mercado EEUU'),
  ('VIG', 'Vanguard Dividend Appreciation ETF', 'factor', 'Empresas con historial de dividendos crecientes'),
  ('MTUM', 'iShares MSCI USA Momentum Factor ETF', 'factor', 'Acciones con mayor momentum de precio');
