CREATE TABLE `theses` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_date` text NOT NULL,
	`title` text NOT NULL,
	`direction` text NOT NULL,
	`narrative` text NOT NULL,
	`catalyst` text,
	`primary_symbol` text NOT NULL,
	`symbols` text NOT NULL,
	`entry_condition_text` text NOT NULL,
	`entry_trigger_price` real NOT NULL,
	`entry_comparator` text NOT NULL,
	`invalidation_price` real NOT NULL,
	`invalidation_reason` text NOT NULL,
	`horizon_days` integer NOT NULL,
	`status` text DEFAULT 'activa' NOT NULL,
	`triggered_at` text,
	`resolved_at` text,
	`outcome_return_pct` real,
	`outcome_vs_spy_pct` real,
	`source_evidence` text,
	`llm_provider` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL
);
